import { expect, test, type Page } from "@playwright/test";

async function openNavigation(page: Page, mode: string) {
  await page.goto("/documents/mock-part-bracket");
  await expect(page.locator("canvas")).toBeVisible();
  await page.getByRole("button", { name: "用户偏好", exact: true }).click();
  await page.getByRole("combobox", { name: "鼠标操作模式" }).click();
  await page.getByText(mode, { exact: true }).click();
  await page.getByRole("dialog", { name: "用户偏好" }).getByRole("button", { name: "关闭", exact: true }).click();
  await expect(page.getByRole("dialog", { name: "用户偏好" })).not.toBeVisible();
  await expect(page.locator(".cad-input-debug")).toContainText(mode === "3DEXPERIENCE CATIA" ? "catia/none" : "solidworks/none");
  const box = (await page.locator("canvas").boundingBox())!;
  return { x: box.x + box.width / 2, y: box.y + box.height / 2, box };
}

test("CATIA native browser chords, sphere, zoom latch, cancellation and persistence", async ({ page }, testInfo) => {
  test.setTimeout(90_000);
  const errors: string[] = []; page.on("pageerror", (error) => errors.push(error.message));
  page.on("console", (message) => { if (/THREE.WebGLProgram|VALIDATE_STATUS|Shader Error/.test(message.text())) errors.push(message.text()); });
  const { x, y } = await openNavigation(page, "3DEXPERIENCE CATIA");
  const debug = page.locator(".cad-input-debug"), camera = page.getByTestId("navigation-camera");
  await page.mouse.move(x, y); const initial = await camera.textContent();
  await page.mouse.wheel(0, 120); await expect(camera).toHaveText(initial!);
  await page.mouse.down({ button: "middle" }); await page.mouse.move(x + 30, y + 15, { steps: 3 });
  await expect(debug).toContainText("catia/pan"); await expect(camera).not.toHaveText(initial!);
  await page.mouse.down({ button: "right" }); await page.mouse.move(x + 80, y + 50, { steps: 4 });
  await expect(debug).toContainText("catia/orbit");
  await expect(debug).toContainText("HUD: hidden");
  await page.screenshot({ path: testInfo.outputPath("catia-native-rotation.png") });
  await page.mouse.up({ button: "right" });
  await expect(debug).toContainText("catia/zoom");
  const rotated = await camera.textContent();
  await page.mouse.move(x + 80, y, { steps: 4 }); await expect(camera).not.toHaveText(rotated!);
  await page.mouse.down({ button: "left" }); await expect(debug).toContainText("catia/orbit");
  await page.mouse.up({ button: "middle" }); await page.mouse.up({ button: "left" });
  await expect(debug).toContainText("catia/none"); await expect(debug).toContainText("HUD: hidden");
  await page.keyboard.down("Control"); await page.mouse.down({ button: "middle" });
  await expect(debug).toContainText("catia/zoom"); await page.keyboard.press("Escape");
  await page.mouse.up({ button: "middle" }); await page.keyboard.up("Control"); await expect(debug).toContainText("catia/none");
  await page.reload(); await expect(page.locator(".workbench-navigation-label")).toHaveText("3DEXPERIENCE CATIA 导航");
  await page.getByRole("button", { name: "用户偏好", exact: true }).click();
  await page.getByRole("switch", { name: "显示旋转球" }).check();
  await page.getByRole("dialog", { name: "用户偏好" }).getByRole("button", { name: "关闭", exact: true }).click();
  await expect(page.getByRole("dialog", { name: "用户偏好" })).not.toBeVisible();
  await page.mouse.move(x, y); await page.mouse.down({ button: "middle" }); await page.mouse.down({ button: "left" });
  await expect(debug).not.toContainText("HUD: hidden");
  await page.screenshot({ path: testInfo.outputPath("catia-optional-sphere.png") });
  await page.mouse.up({ button: "left" }); await page.mouse.up({ button: "middle" });
  await page.reload();
  await page.getByRole("button", { name: "用户偏好", exact: true }).click();
  await expect(page.getByRole("switch", { name: "显示旋转球" })).toBeChecked();
  expect(errors).toEqual([]);
});

test("SOLIDWORKS modifiers, entity reference, middle double click and focus loss", async ({ page }, testInfo) => {
  test.setTimeout(90_000);
  const errors: string[] = []; page.on("pageerror", (error) => errors.push(error.message));
  page.on("console", (message) => { if (/THREE.WebGLProgram|VALIDATE_STATUS|Shader Error/.test(message.text())) errors.push(message.text()); });
  const { x, y } = await openNavigation(page, "SOLIDWORKS");
  const debug = page.locator(".cad-input-debug"), camera = page.getByTestId("navigation-camera");
  await page.mouse.move(x, y); const initial = await camera.textContent();
  await page.mouse.click(x, y, { button: "middle" });
  await expect(debug).toContainText("Reference: face"); await expect(camera).toHaveText(initial!);
  await page.screenshot({ path: testInfo.outputPath("solidworks-reference.png") });
  await page.mouse.down({ button: "middle" }); await page.mouse.move(x + 40, y + 20, { steps: 3 });
  await expect(debug).toContainText("solidworks/orbit"); await expect(camera).not.toHaveText(initial!);
  await page.keyboard.down("Control"); await expect(debug).toContainText("solidworks/pan");
  await page.mouse.move(x + 60, y + 40, { steps: 3 });
  await page.keyboard.up("Control"); await page.keyboard.down("Shift"); await expect(debug).toContainText("solidworks/zoom");
  await page.mouse.move(x + 60, y, { steps: 3 });
  await page.keyboard.up("Shift"); await page.keyboard.down("Alt"); await expect(debug).toContainText("solidworks/roll");
  await page.mouse.move(x + 90, y, { steps: 3 }); await page.keyboard.up("Alt"); await page.mouse.up({ button: "middle" });
  await expect(debug).toContainText("Reference: none");
  const moved = await camera.textContent();
  await page.mouse.dblclick(x, y, { button: "middle", delay: 70 }); await expect(camera).not.toHaveText(moved!);
  await page.mouse.down({ button: "middle" }); await page.evaluate(() => window.dispatchEvent(new Event("blur")));
  await expect(debug).toContainText("solidworks/none"); await page.mouse.up({ button: "middle" });
  expect(errors).toEqual([]);
});

test("orthographic detail navigation, isometric shortcut and sketch view round trip", async ({ page }, testInfo) => {
  test.setTimeout(90_000);
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  page.on("console", (message) => { if (/THREE.WebGLProgram|VALIDATE_STATUS|Shader Error/.test(message.text())) errors.push(message.text()); });
  await page.goto("/documents/mock-part-bracket");
  const canvas = page.locator("canvas"), camera = page.getByTestId("navigation-camera");
  const projection = page.getByTestId("navigation-projection");
  await expect(projection).toContainText("orthographic");
  const bounds = (await canvas.boundingBox())!;
  const x = bounds.x + bounds.width / 2, y = bounds.y + bounds.height / 2;
  const initialScale = await projection.textContent();
  await page.mouse.move(x, y); await page.mouse.wheel(0, -1800);
  await expect(projection).not.toHaveText(initialScale!);
  await canvas.focus();
  let scale = await projection.textContent();
  await page.mouse.down({ button: "right" }); await page.mouse.move(x + 23, y + 15, { steps: 3 }); await page.mouse.up({ button: "right" });
  const rotatedCamera = await camera.textContent();
  await page.keyboard.press("1");
  await expect(camera).not.toHaveText(rotatedCamera!);
  await expect(projection).not.toHaveText(scale!);
  await expect(projection).toHaveText(initialScale!);
  scale = await projection.textContent();
  await page.screenshot({ path: testInfo.outputPath("isometric-fit-grid.png") });
  const iso = await camera.textContent();
  await page.keyboard.press("1"); await expect(camera).toHaveText(iso!);
  // Beyond the old 1200-unit grid: the background plane still fills the viewport.
  await page.mouse.wheel(0, 3000); await expect(projection).not.toHaveText(scale!);
  await page.mouse.down({ button: "middle" }); await page.mouse.move(x + 200, y + 80, { steps: 3 }); await page.mouse.up({ button: "middle" });
  await page.screenshot({ path: testInfo.outputPath("unbounded-grid-zoomed-out.png") });
  await page.keyboard.press("1"); await expect(camera).toHaveText(iso!);
  await page.mouse.down({ button: "middle" }); await page.mouse.move(x + 40, y + 25, { steps: 3 }); await page.mouse.up({ button: "middle" });
  await expect(projection).toHaveText(scale!);
  const beforeSketch = await camera.textContent();
  const filter = page.getByRole("textbox", { name: "筛选模型结构" });
  await filter.fill("XY Plane");
  await page.getByRole("treeitem").filter({ hasText: "XY Plane" }).click();
  await page.getByRole("button", { name: "草图", exact: true }).click();
  await expect(page.getByRole("button", { name: "退出草图", exact: true })).toBeVisible();
  await expect(projection).toHaveText(scale!);
  await page.mouse.move(x, y); await page.mouse.wheel(0, 250);
  await expect(projection).not.toHaveText(scale!);
  await page.getByRole("button", { name: "退出草图", exact: true }).click();
  await expect(camera).toHaveText(beforeSketch!);
  await page.screenshot({ path: testInfo.outputPath("orthographic-detail-restored.png") });
  expect(errors).toEqual([]);
});

test("selected face sketch keeps scale and restores the modelling view", async ({ page }) => {
  await page.goto("/documents/mock-part-bracket");
  const camera = page.getByTestId("navigation-camera"), projection = page.getByTestId("navigation-projection");
  await expect(projection).toContainText("orthographic");
  const box = (await page.locator("canvas").boundingBox())!;
  await page.mouse.click(box.x + box.width / 2, box.y + box.height / 2);
  const before = await camera.textContent(), scale = await projection.textContent();
  const sketch = page.getByRole("button", { name: "草图", exact: true });
  await expect(sketch).toBeEnabled(); await sketch.click();
  const exit = page.getByRole("button", { name: "退出草图", exact: true });
  await expect(exit).toBeVisible(); await expect(projection).toHaveText(scale!);
  await expect(camera).not.toHaveText(before!);
  await exit.click(); await expect(camera).toHaveText(before!);
});

test("switching documents clears the previous sketch camera session", async ({ page }) => {
  test.setTimeout(90_000);
  await page.goto("/documents/mock-part-bracket");
  await expect(page.getByTestId("navigation-projection")).toContainText("orthographic");
  await page.getByRole("button", { name: "文档中心", exact: true }).click();
  await page.locator(".document-card").filter({ hasText: "Frame Assembly" }).locator(".thumbnail-button").dblclick();
  await expect(page.getByRole("button", { name: "插入", exact: true })).toBeVisible();
  const assemblyCamera = await page.getByTestId("navigation-camera").textContent();
  await page.locator(".document-tab-switch").filter({ hasText: "Mounting Bracket" }).click();
  await expect(page.getByRole("button", { name: "草图", exact: true })).toBeVisible();
  const filter = page.getByRole("textbox", { name: "筛选模型结构" });
  await filter.fill("XY Plane");
  await page.getByRole("treeitem").filter({ hasText: "XY Plane" }).click();
  await page.getByRole("button", { name: "草图", exact: true }).click();
  await expect(page.getByRole("button", { name: "退出草图", exact: true })).toBeVisible();
  await page.locator(".document-tab-switch").filter({ hasText: "Frame Assembly" }).click();
  await expect(page.getByRole("button", { name: "插入", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "退出草图", exact: true })).not.toBeVisible();
  await expect(page.getByTestId("navigation-camera")).toHaveText(assemblyCamera!);
});

test("sketch normal view, persistent world context and exit selection synchronization", async ({ page }, testInfo) => {
  test.setTimeout(90_000);
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  page.on("console", (message) => { if (/THREE.WebGLProgram|VALIDATE_STATUS|Shader Error/.test(message.text())) errors.push(message.text()); });
  await page.goto("/documents/mock-part-bracket");
  const filter = page.getByRole("textbox", { name: "筛选模型结构" });
  await filter.fill("Sketch 1");
  const sketch = page.getByRole("treeitem").filter({ hasText: "Sketch 1" });
  await sketch.dblclick();
  const normal = page.getByRole("button", { name: "正对草图平面", exact: true });
  await expect(normal).toBeVisible();
  const camera = page.getByTestId("navigation-camera"), projection = page.getByTestId("navigation-projection");
  const initial = await camera.textContent(), scale = await projection.textContent();
  const box = (await page.locator("canvas").boundingBox())!;
  const x = box.x + box.width/2, y = box.y + box.height/2;
  await page.mouse.move(x,y); await page.mouse.down({button:"right"});
  await page.mouse.move(x+110,y+80,{steps:5}); await page.mouse.up({button:"right"});
  await expect(camera).not.toHaveText(initial!);
  await page.screenshot({path:testInfo.outputPath("sketch-oblique-world-and-plane-grids.png")});
  await normal.click(); await expect(projection).toHaveText(scale!);
  await expect.poll(async () => (await camera.textContent())?.split(" / ")[1]).toBe(initial!.split(" / ")[1]);
  await page.mouse.move(x,y); await page.mouse.wheel(0,2300); await expect(projection).not.toHaveText(scale!);
  await page.screenshot({path:testInfo.outputPath("sketch-infinite-plane-grid.png")});
  await page.getByRole("button",{name:"退出草图",exact:true}).click();
  const selection = page.getByTestId("viewport-selection");
  await expect(sketch).toHaveAttribute("aria-selected","true");
  await expect(selection).toHaveAttribute("data-count","1");
  await expect.poll(async () => Number(await selection.getAttribute("data-highlighted"))).toBeGreaterThan(0);
  await expect(page.getByRole("button",{name:"拉伸",exact:true})).toBeEnabled();
  await page.screenshot({path:testInfo.outputPath("sketch-exit-selected.png")});
  await page.mouse.click(box.x+box.width-12,box.y+12);
  await expect(selection).toHaveAttribute("data-count","0");
  await expect(sketch).toHaveAttribute("aria-selected","false");
  await expect(page.getByRole("button",{name:"拉伸",exact:true})).toBeDisabled();
  expect(errors).toEqual([]);
});
