-- P10 workbench UX: one toolbar owns one user-intent category. Capture,
-- navigation profile and units are global preferences rather than commands.
-- The project has no released persistent-data contract, so this migration
-- replaces the experimental catalog instead of maintaining duplicate layouts.
DELETE FROM occccad.ui_toolbar_items;
DELETE FROM occccad.ui_toolbars;

INSERT INTO occccad.ui_toolbars(id,name,workbench,position,style_key,sort_order) VALUES
('selection','选择','ALL','top-left','standard',0),
('part-sketch','草图入口','PART_DESIGN','top-left','part',10),
('part-features','实体特征','PART_DESIGN','top-left','part',20),
('part-knowledge','参数与接口','PART_DESIGN','top-left','part',30),
('part-datums','基准','PART_DESIGN','top-left','part',40),
('sketch-lifecycle','草图会话','SKETCHER','top-left','sketch',10),
('sketch-projection','外部几何','SKETCHER','top-left','sketch',20),
('sketch-primitives','草图基本元素','SKETCHER','top-left','sketch',30),
('sketch-profiles','草图轮廓','SKETCHER','top-left','sketch',40),
('sketch-geometric-constraints','几何约束','SKETCHER','top-left','sketch',50),
('sketch-dimensional-constraints','尺寸约束','SKETCHER','top-left','sketch',60),
('product-structure','产品结构','ASSEMBLY_DESIGN','top-left','assembly',10),
('product-interface','产品接口','ASSEMBLY_DESIGN','top-left','assembly',20),
('assembly-positioning','组件定位','ASSEMBLY_DESIGN','top-left','assembly',30),
('assembly-constraints','装配约束','ASSEMBLY_DESIGN','top-left','assembly',40),
('history','历史','ALL','top-center','standard',70),
('collaboration','协作','ALL','top-center','standard',80),
('view-navigation','视图','ALL','top-right','standard',90),
('debug','诊断','ALL','bottom-right','debug',100);

INSERT INTO occccad.ui_toolbar_items(toolbar_id,command_id,name,help_text,icon_key,group_key,sort_order,repeatable) VALUES
('selection','tool.select','选择','选择视图区或结构树中的对象。','select','primary',10,false),
('part-sketch','sketch.start','草图','选择基准面创建草图，或选择已有草图进入编辑。','sketch','primary',10,false),
('part-features','part.pad','拉伸','沿草图平面法向拉伸所选闭合草图。','pad','primary',10,false),
('part-features','part.pocket','切除','沿草图平面法向生成工具体，并从当前 Body 移除材料。','pocket','primary',20,false),
('part-features','part.revolve','旋转','绕草图中的构造线旋转闭合区域并应用到当前 Body。','revolve','primary',30,false),
('part-knowledge','part.parameters','参数','集中查看、编辑并复用当前 Part 的参数。','parameters','primary',10,false),
('part-knowledge','part.publications','发布','创建和管理可跨文档引用的稳定几何与参数契约。','publication','primary',20,false),
('part-datums','part.datum-plane','基准面','以所选平面为参考创建偏置基准面。','datum-plane','primary',10,false),
('part-datums','part.datum-axis','基准轴','以显式原点和方向创建基准轴。','datum-axis','primary',20,false),
('sketch-lifecycle','sketch.finish','退出草图','结束当前草图编辑并返回 Part Design。','finish','primary',10,false),
('sketch-projection','sketch.project','投影','将已有实体的边或顶点关联投影为外部几何。','project','primary',10,true),
('sketch-primitives','sketch.point','点','在活动草图中创建点；双击按钮进入连续创建。','point','primary',10,true),
('sketch-primitives','sketch.line','直线','用起点和终点创建直线；双击按钮连续创建。','line','primary',20,true),
('sketch-primitives','sketch.arc','圆弧','依次指定圆心、起点和终点创建圆弧。','arc','primary',30,true),
('sketch-primitives','sketch.polyline','多段线','连续创建相接线段，双击或 Enter 完成。','polyline','primary',40,true),
('sketch-primitives','sketch.spline','过点曲线','创建经过采集点的插值曲线，双击或 Enter 完成。','spline','primary',50,true),
('sketch-profiles','sketch.rectangle','矩形','用两个对角点创建带内部连接和方向约束的矩形。','rectangle','primary',10,true),
('sketch-profiles','sketch.polygon','正六边形','用中心和顶点创建正六边形。','polygon','primary',20,true),
('sketch-profiles','sketch.circle','圆','用圆心和圆周点创建圆。','circle','primary',30,true),
('sketch-profiles','sketch.slot','长圆孔','用中心线和半径创建长圆孔轮廓。','slot','primary',40,true),
('sketch-geometric-constraints','sketch.constraint.coincident','重合','使两个点引用重合。','coincident','primary',10,true),
('sketch-geometric-constraints','sketch.constraint.parallel','平行','使两条直线或直线与基准轴平行。','parallel','primary',20,true),
('sketch-geometric-constraints','sketch.constraint.fixed','固定','固定所选几何的当前参数。','fixed','primary',30,true),
('sketch-geometric-constraints','sketch.constraint.horizontal','水平','使直线平行于草图 U 轴。','horizontal','primary',40,true),
('sketch-geometric-constraints','sketch.constraint.vertical','垂直','使直线平行于草图 V 轴。','vertical','primary',50,true),
('sketch-geometric-constraints','sketch.constraint.perpendicular','垂直相交','使两条直线方向互相垂直。','perpendicular','primary',60,true),
('sketch-geometric-constraints','sketch.constraint.tangent','相切','使支持的直线、圆或圆弧相切。','tangent','primary',70,true),
('sketch-geometric-constraints','sketch.constraint.equal','相等','使两条线等长，或使圆和圆弧等半径。','equal','primary',80,true),
('sketch-geometric-constraints','sketch.constraint.concentric','同心','使两个圆形元素共享圆心。','concentric','primary',90,true),
('sketch-geometric-constraints','sketch.constraint.point_on_object','点在对象上','约束一个点位于直线、圆或圆弧上。','point-on-object','primary',100,true),
('sketch-geometric-constraints','sketch.constraint.midpoint','中点','约束一个点位于直线中点。','midpoint','primary',110,true),
('sketch-geometric-constraints','sketch.constraint.symmetry','对称','使用直线/基准轴做轴对称，或使用点/原点做中心对称。','symmetry','primary',120,true),
('sketch-dimensional-constraints','sketch.dimension.linear','线性尺寸','创建线长、点点距离或点线距离尺寸。','distance','primary',10,true),
('sketch-dimensional-constraints','sketch.constraint.radius','半径','设置圆或圆弧的半径尺寸。','radius','primary',20,true),
('sketch-dimensional-constraints','sketch.constraint.angle','角度','设置两条直线或直线与基准轴的夹角。','angle','primary',30,true),
('product-structure','product.insert','插入','向 Product 插入 Part 或 Product 实例。','insert','primary',10,false),
('product-interface','product.publications','发布','转发子 Part Publication，形成稳定 Product 装配接口。','publication','primary',10,false),
('product-interface','product.release','产品版本','打开不可变产品版本中心。','release','primary',20,false),
('assembly-positioning','assembly.move','移动组件','选择装配实例并使用三维操纵器移动。','move','primary',10,false),
('assembly-constraints','assembly.fix','固定','固定所选装配实例的当前刚体位置。','fixed','primary',10,false),
('assembly-constraints','assembly.rigid','固连','保持两个装配实例之间的当前相对刚体位姿。','link','primary',20,false),
('assembly-constraints','assembly.coincident','重合','使两个基准点、轴或平面重合。','coincident','primary',30,false),
('assembly-constraints','assembly.concentric','同心','使所选两条基准轴同轴。','concentric','primary',40,false),
('assembly-constraints','assembly.angle','角度','约束两个基准轴或平面的夹角。','angle','primary',50,false),
('assembly-constraints','assembly.distance','距离','约束两个基准元素的距离。','distance','primary',60,false),
('history','edit.undo','撤销','补偿最近一个可撤销的领域事务。','undo','primary',10,false),
('history','edit.redo','重做','重新应用最近一个已撤销的领域事务。','redo','primary',20,false),
('history','history.version','创建版本','为当前 Revision 创建命名版本。','version','primary',30,false),
('collaboration','document.share','共享','管理当前文档的访问授权。','share','primary',10,false),
('view-navigation','view.fit','适合窗口','调整相机以显示全部模型。','fit','primary',10,false),
('view-navigation','view.top','顶视图','切换到顶视图。','top-view','primary',20,false),
('view-navigation','view.front','前视图','切换到前视图。','front-view','primary',30,false),
('view-navigation','view.right','右视图','切换到右视图。','right-view','primary',40,false),
('view-navigation','view.iso','等轴测','切换到等轴测标准视图。','isometric','primary',50,false),
('debug','debug.download','下载诊断包','导出当前文档、草图、Workspace、事务和求值诊断数据。','debug','primary',10,false);
